return {
PlaceObj('ModItemBuildingTemplate', {
	'Group', "Production",
	'Id', "AdvancedWasteRockProcessor",
	'template_class', "WasteRockProcessor",
	'pin_rollover_hint', T(545009712719, --[[ModItemBuildingTemplate AdvancedWasteRockProcessor pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"),
	'pin_rollover_hint_xbox', T(583729348586, --[[ModItemBuildingTemplate AdvancedWasteRockProcessor pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"),
	'construction_cost_Metals', 20000,
	'construction_cost_MachineParts', 3000,
	'build_points', 5000,
	'is_tall', true,
	'dome_forbidden', true,
	'force_extend_bb_during_placement_checks', 12000,
	'upgrade1_id', "AWRP_FueledProcessor",
	'upgrade1_display_name', T(243974558084, --[[ModItemBuildingTemplate AdvancedWasteRockProcessor upgrade1_display_name]] "Fueled Processor"),
	'upgrade1_description', T(666545924431, --[[ModItemBuildingTemplate AdvancedWasteRockProcessor upgrade1_description]] "+<upgrade1_mul_value_1>% Concrete production as long as the building is supplied with Fuel. Does not consume additional waste rock."),
	'upgrade1_icon', "UI/Icons/Upgrades/fueled_extractor_01.tga",
	'upgrade1_upgrade_cost_MachineParts', 2000,
	'upgrade1_mod_label_1', "AdvancedWasteRockProcessor",
	'upgrade1_mod_prop_id_1', "production_per_day3",
	'upgrade1_mul_value_1', 100,
	'upgrade1_mod_label_2', "AdvancedWasteRockProcessor",
	'upgrade1_mod_prop_id_2', "consumption_amount",
	'upgrade1_add_value_2', -3,
	'upgrade1_consumption_resource_type', "Fuel",
	'upgrade1_consumption_amount', 800,
	'upgrade1_consumption_resource_stockpile_spot_name', "",
	'maintenance_resource_type', "MachineParts",
	'consumption_resource_type', "WasteRock",
	'consumption_max_storage', 20000,
	'consumption_amount', 7500,
	'display_name', T(300359920319, --[[ModItemBuildingTemplate AdvancedWasteRockProcessor display_name]] "Advanced Waste Rock Processor"),
	'display_name_pl', T(963985047773, --[[ModItemBuildingTemplate AdvancedWasteRockProcessor display_name_pl]] "Advanced Waste Rock Processors"),
	'description', T(521995926602, --[[ModItemBuildingTemplate AdvancedWasteRockProcessor description]] "Extracts Metals and Rare Metals from Waste Rock. Also producers construction materials (concrete)"),
	'build_category', "Production",
	'display_icon', "UI/Icons/Buildings/waste_rock_processor.tga",
	'build_pos', 8,
	'entity', "WasteRockProcessor",
	'encyclopedia_id', "WasteRockProcessor",
	'encyclopedia_image', "UI/Encyclopedia/WasteRockProcessor.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palette_color1', "mining_accent_1",
	'palette_color2', "mining_base",
	'palette_color3', "mining_base",
	'demolish_sinking', range(20, 20),
	'demolish_tilt_angle', range(600, 600),
	'demolish_debris', 0,
	'sponsor_name1', "BRIC",
	'sponsor_status1', "required",
	'resource_produced1', "PreciousMetals",
	'max_storage1', 10000,
	'resource_produced2', "Metals",
	'max_storage2', 10000,
	'resource_produced3', "Concrete",
	'production_per_day3', 2000,
	'electricity_consumption', 10000,
}),
PlaceObj('ModItemCode', {
	'FileName', "Code/Script.lua",
}),
PlaceObj('ModItemMissionSponsorPreset', {
	Drone = 6,
	DroneHub = 1,
	Electronics = 10,
	FuelFactory = 1,
	MachineParts = 15,
	MoistureVaporator = 1,
	OrbitalProbe = 3,
	Polymers = 10,
	RCDriller = 1,
	SortKey = 9001,
	StirlingGenerator = 1,
	banners_name = "Russia",
	cargo = 50000,
	challenge_mod = 100,
	colony_color_scheme = "red_steel",
	default_logo = "Russia",
	default_skin = "Facet",
	display_name = T(543688288007, --[[ModItemMissionSponsorPreset Default BRIC display_name]] "BRIC"),
	effect = T(878698187148, --[[ModItemMissionSponsorPreset Default BRIC effect]] "Research per Sol: 150\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>RC Driller</color> - a special rover that can extract resources from underground deposits but wastes some of the deposit\n- <color em>Large Supply Pod</color> - a special supply pod that can carry more cargo\n- <color em>Advanced Waste Rock Reprocessor</color> - turns waste rock into metals, rare metals, and concrete\n- Bonus Tech: <color em>Fueled Extractors</color> (extractor upgrade that boosts production but consumes Fuel)\n- Bonus Tech: <color em>Low-G Engineering</color> (allows medium domes to be built)\n- Bonus Tech: <color em>Compact Passanger Module</color> (passenger rockets carry 10 additional colonists)\n- Applicants are generated 25% faster\n- Building construction costs of domes and inside buildings in <em>Metals & Concrete</em> reduced by 20%\n- Fuel Refinery prefab costs 50% less\n- Rockets have extended travel time <color em>(drawback)</color>"),
	funding = 7250,
	goal_1_param_1 = "8",
	goal_2_param_1 = "1000",
	goal_2_param_2 = "",
	goal_3_param_1 = "200",
	goal_3_param_2 = "Metals",
	goal_4_param_1 = "4",
	goal_4_param_2 = "",
	goal_5_param_1 = "50",
	goal_image_1 = "UI/Messages/Goals/mission_goal_07.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_04.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_05.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_10.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_02.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/supply_pod.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/drone.tga",
	goal_pin_image_3 = "UI/Icons/Buildings/funding.tga",
	goal_pin_image_4 = "UI/Icons/Colonists/Femaleengineer.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/research.tga",
	group = "Default",
	id = "BRIC",
	initial_applicants = 120,
	initial_techs_unlocked = 1,
	lock_name1 = "RCDriller",
	lock_value1 = "unlocked",
	modifier_name1 = "FuelFactory",
	modifier_value1 = -50,
	name = "BRIC",
	pod_class = "DropPod",
	research_points = 150,
	research_points_per_explored_sector = 125,
	reward_effect_1 = PlaceObj('RewardSupplyPods', {
		'Amount', 8,
	}),
	reward_effect_2 = PlaceObj('RewardPrefab', {
		'Amount', 25,
		'Prefab', "DronePrefab",
	}),
	reward_effect_3 = PlaceObj('RewardFunding', {
		'Amount', 2000000000,
	}),
	reward_effect_4 = PlaceObj('RewardApplicants', {
		'Amount', 20,
		'Trait', "Enthusiast",
		'Specialization', "engineer",
	}),
	reward_effect_5 = PlaceObj('RewardResearchPoints', {
		'Amount', 10000,
	}),
	sponsor_goal_1 = "Deposits",
	sponsor_goal_2 = "ConvertWasteRock",
	sponsor_goal_3 = "ProduceUndergroundResource",
	sponsor_goal_4 = "DomeSpires",
	sponsor_goal_5 = "DeepScanSectors",
	sponsor_nation_name1 = "Russian",
	sponsor_nation_name2 = "Bulgarian",
	sponsor_nation_name3 = "Chinese",
	sponsor_nation_name4 = "Indian",
	sponsor_nation_name5 = "Brazilian",
	sponsor_nation_percent1 = 20,
	sponsor_nation_percent2 = 5,
	sponsor_nation_percent3 = 30,
	sponsor_nation_percent4 = 25,
	sponsor_nation_percent5 = 20,
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = 100,
		Prop = "TravelTimeEarthMars",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Robotics",
		Research = "FueledExtractors",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = 100,
		Prop = "TravelTimeMarsEarth",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -20,
		Prop = "ApplicantGenerationInterval",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Engineering",
		Research = "CompactPassengerModule",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Engineering",
		Research = "LowGEngineering",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Domes_Construction",
		Percent = -20,
		Prop = "construction_cost_Concrete",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Domes_Construction",
		Percent = -20,
		Prop = "construction_cost_Metals",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "InsideBuildings_Construction",
		Percent = -20,
		Prop = "construction_cost_Concrete",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "InsideBuildings_Construction",
		Percent = -20,
		Prop = "construction_cost_Metals",
	}),
	PlaceObj('Effect_UnlockUpgrade', {
		Upgrade = "AWRP_FueledProcessor",
	}),
}),
}
